spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.DoubleSerializer
      acks: all
      retries: 1000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.DoubleDeserializer
      group-id: taxi-app
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval: 5000

app:
  kafka:
    input-topic: input_topic
    output-topic: output_topic
    producer:
      enable:
        idempotence: true
      max:
        in:
          flight:
            requests:
              per:
                connection: 5
