spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 1000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: java-app
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000

app:
  kafka:
    topic: some_topic
    producer:
      enable:
        idempotence: true
      max:
        in:
          flight:
            requests:
              per:
                connection: 5
